# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bigcubecat/__folder__/APP/GameOfLife

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bigcubecat/__folder__/APP/GameOfLife

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bigcubecat/__folder__/APP/GameOfLife/CMakeFiles /home/bigcubecat/__folder__/APP/GameOfLife/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bigcubecat/__folder__/APP/GameOfLife/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameOfLife

# Build rule for target.
GameOfLife: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLife
.PHONY : GameOfLife

# fast build rule for target.
GameOfLife/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/build
.PHONY : GameOfLife/fast

#=============================================================================
# Target rules for targets named GameOfLife_autogen

# Build rule for target.
GameOfLife_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLife_autogen
.PHONY : GameOfLife_autogen

# fast build rule for target.
GameOfLife_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife_autogen.dir/build.make CMakeFiles/GameOfLife_autogen.dir/build
.PHONY : GameOfLife_autogen/fast

Canvas.o: Canvas.cpp.o

.PHONY : Canvas.o

# target to build an object file
Canvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/Canvas.cpp.o
.PHONY : Canvas.cpp.o

Canvas.i: Canvas.cpp.i

.PHONY : Canvas.i

# target to preprocess a source file
Canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/Canvas.cpp.i
.PHONY : Canvas.cpp.i

Canvas.s: Canvas.cpp.s

.PHONY : Canvas.s

# target to generate assembly for a file
Canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/Canvas.cpp.s
.PHONY : Canvas.cpp.s

GameOfLife_autogen/mocs_compilation.o: GameOfLife_autogen/mocs_compilation.cpp.o

.PHONY : GameOfLife_autogen/mocs_compilation.o

# target to build an object file
GameOfLife_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/GameOfLife_autogen/mocs_compilation.cpp.o
.PHONY : GameOfLife_autogen/mocs_compilation.cpp.o

GameOfLife_autogen/mocs_compilation.i: GameOfLife_autogen/mocs_compilation.cpp.i

.PHONY : GameOfLife_autogen/mocs_compilation.i

# target to preprocess a source file
GameOfLife_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/GameOfLife_autogen/mocs_compilation.cpp.i
.PHONY : GameOfLife_autogen/mocs_compilation.cpp.i

GameOfLife_autogen/mocs_compilation.s: GameOfLife_autogen/mocs_compilation.cpp.s

.PHONY : GameOfLife_autogen/mocs_compilation.s

# target to generate assembly for a file
GameOfLife_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/GameOfLife_autogen/mocs_compilation.cpp.s
.PHONY : GameOfLife_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

model/Life.o: model/Life.cpp.o

.PHONY : model/Life.o

# target to build an object file
model/Life.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/model/Life.cpp.o
.PHONY : model/Life.cpp.o

model/Life.i: model/Life.cpp.i

.PHONY : model/Life.i

# target to preprocess a source file
model/Life.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/model/Life.cpp.i
.PHONY : model/Life.cpp.i

model/Life.s: model/Life.cpp.s

.PHONY : model/Life.s

# target to generate assembly for a file
model/Life.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/model/Life.cpp.s
.PHONY : model/Life.cpp.s

model/Worker.o: model/Worker.cpp.o

.PHONY : model/Worker.o

# target to build an object file
model/Worker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/model/Worker.cpp.o
.PHONY : model/Worker.cpp.o

model/Worker.i: model/Worker.cpp.i

.PHONY : model/Worker.i

# target to preprocess a source file
model/Worker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/model/Worker.cpp.i
.PHONY : model/Worker.cpp.i

model/Worker.s: model/Worker.cpp.s

.PHONY : model/Worker.s

# target to generate assembly for a file
model/Worker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/model/Worker.cpp.s
.PHONY : model/Worker.cpp.s

panel/CoordsPanel.o: panel/CoordsPanel.cpp.o

.PHONY : panel/CoordsPanel.o

# target to build an object file
panel/CoordsPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/panel/CoordsPanel.cpp.o
.PHONY : panel/CoordsPanel.cpp.o

panel/CoordsPanel.i: panel/CoordsPanel.cpp.i

.PHONY : panel/CoordsPanel.i

# target to preprocess a source file
panel/CoordsPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/panel/CoordsPanel.cpp.i
.PHONY : panel/CoordsPanel.cpp.i

panel/CoordsPanel.s: panel/CoordsPanel.cpp.s

.PHONY : panel/CoordsPanel.s

# target to generate assembly for a file
panel/CoordsPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/panel/CoordsPanel.cpp.s
.PHONY : panel/CoordsPanel.cpp.s

panel/Panel.o: panel/Panel.cpp.o

.PHONY : panel/Panel.o

# target to build an object file
panel/Panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/panel/Panel.cpp.o
.PHONY : panel/Panel.cpp.o

panel/Panel.i: panel/Panel.cpp.i

.PHONY : panel/Panel.i

# target to preprocess a source file
panel/Panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/panel/Panel.cpp.i
.PHONY : panel/Panel.cpp.i

panel/Panel.s: panel/Panel.cpp.s

.PHONY : panel/Panel.s

# target to generate assembly for a file
panel/Panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/panel/Panel.cpp.s
.PHONY : panel/Panel.cpp.s

view/Camera.o: view/Camera.cpp.o

.PHONY : view/Camera.o

# target to build an object file
view/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/view/Camera.cpp.o
.PHONY : view/Camera.cpp.o

view/Camera.i: view/Camera.cpp.i

.PHONY : view/Camera.i

# target to preprocess a source file
view/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/view/Camera.cpp.i
.PHONY : view/Camera.cpp.i

view/Camera.s: view/Camera.cpp.s

.PHONY : view/Camera.s

# target to generate assembly for a file
view/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/view/Camera.cpp.s
.PHONY : view/Camera.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GameOfLife_autogen"
	@echo "... GameOfLife"
	@echo "... Canvas.o"
	@echo "... Canvas.i"
	@echo "... Canvas.s"
	@echo "... GameOfLife_autogen/mocs_compilation.o"
	@echo "... GameOfLife_autogen/mocs_compilation.i"
	@echo "... GameOfLife_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... model/Life.o"
	@echo "... model/Life.i"
	@echo "... model/Life.s"
	@echo "... model/Worker.o"
	@echo "... model/Worker.i"
	@echo "... model/Worker.s"
	@echo "... panel/CoordsPanel.o"
	@echo "... panel/CoordsPanel.i"
	@echo "... panel/CoordsPanel.s"
	@echo "... panel/Panel.o"
	@echo "... panel/Panel.i"
	@echo "... panel/Panel.s"
	@echo "... view/Camera.o"
	@echo "... view/Camera.i"
	@echo "... view/Camera.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

