// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_Canvas.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "NLOY5YBGEN/moc_Worker.cpp"
#include "2M4IF6KQHC/moc_CoordsPanel.cpp"
#include "2M4IF6KQHC/moc_Panel.cpp"
